src/Plugin.php
Fixes issue where plugin still tries to execute PHP_CodeSniffer, even if it is not installed.
In case this plugin was installed globally and PHP_CodeSniffer is not in the repository you are working on.
=> Bugfix: Plugin fails when PHP_CodeSniffer is not installed

.lgtm
Enforcement is now done by Github's native required pull requests review method.
=> Removal of lgtm.co

README.md, src/Plugin.php
- Search package sub-folders to a limited depth (< 4), to find PHP CodeSniffer standards
- Only add installed paths where a `ruleset.xml` exists in a standards sub-folder
- Update README to reflect requirements change
- Fix some spelling mistakes in comments
I want to use your excellent installer plugin with the Drupal PHP CodeSniffer standards. Their package uses a subfolder, one deeper than the repository root, which they're unable to change. I am sure there are other examples where Standards may be one or two folders deeper than the current installer allows.
- @frenck
=> Support existing standards packages with subfolders

src/Plugin.php
1. Output to console config changes being made
1. When `-v` (verbose) flag is used, also output PHP CodeSniffer config command results
Fixes #7
=> Show config actions and a result as Console output

.gitattributes, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
- Ensure issues created contain appropriate detail
- Improve quality of pull request descriptions created by contributors
- Prevent Github templates and unnecessary developer files from being exported in Git archives (ie. Packagist distribution archives)
#9
=> Github contribution templates

src/Plugin.php
Fix for issue #4.
This PR expose a new method `run`. This can be use from a `composer.json` file like this:
```
{
"name": "potherca/phpcodesniffer-composer-installer-example",
"description": "Example to demonstrate the working of the dealerdirect/phpcodesniffer-composer-installer package.",
"require": {
"dealerdirect/phpcodesniffer-composer-installer": "*",
},
"scripts": {
"run-phpcodesniffer-composer-installer": [
"Dealerdirect\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\Plugin::run"
]
}
}
```
Beside this feature I have also done some minor code cleanup and added more message for in verbose mode.
=> Adds static function to call the Plugin::onDependenciesChangedEvent() method

CONTRIBUTING.md, LICENSE.md, README.md
Update documentation on several parts:
- To match our Markdown code guidelines
- Updated copyright years in preparation of the new release
- Updated badges/shields
- Added [project stage](http://bl.ocks.org/potherca/raw/a2ae67caa3863a299ba0/) badge 
- Added Scrutinizer badge
- Added latests version on Packagist badge
This PR prepares for a next release as requested in #11
=> Improved documentation

src/Plugin.php
Changed coding standards starting search depth from `> 1` to `>= 1`.
#13 Plugin not working correctly when sniffs install depth is equal to "1"
=> Fixed #13: Incorrect coding standards search depth

src/Plugin.php
The root package needs a different install path (since it's not really installed, it's already there) so right now the install fails. The instance of check prevents the package from being installed if the package has the RootPackageInterface.
Fix for #19
I had some spare minutes and wanted to continue my sniff so I just fixed it online on Github so I won't mess up the formatting.
=> Added instanceof check to prevent root package from being installed

src/Plugin.php
This change adds support for having PHP_CodeSniffer standards in the root package.
Implements: #20 Check the root package for sniffs to install
=> Added support for having coding standards in the root package

.travis.yml, src/Plugin.php
I got annoyed at all of the pull-requests having a red :x: next to builds. 
This merge request fixes that by adding a `.travis.yml` file that triggers a PHP build.
It tries to find a balance between speed and quality.
I've also added a fix for a PHP CodeSniffer violation (one line exceeded 120 characters).
Part of issue #9  
The `dealerdirect/qa-tools` is installed on the Travis machine to run QA checks.
Currently this means the build for unsupported PHP versions (5.3, 5.4, 5.4) will fail because `qa-tools` requires at least 5.6.
At a later stage, these builds could be made to pass. Such a solution is not within scope for this merge-request.
=> Adds Travis-CI configuration file.

src/Plugin.php
Changed they way paths are put into PHP_CodeSniffer based on Composer being executes globally or not. Local repositories (project folder) installations will use relative paths from the PHP_CodeSniffer installation directory to the directory containing the coding standard.
The behaviour for globally installed instances will keep using absolute paths; unchanged.
#20 Install sniffs with relative paths in CodeSniffer.conf
=> CHANGE: Local projects uses relative paths to their coding standards

README.md
Documents the ability to execute the main plugin functionality "directly" (through composer) in the "Usage" section of the README file.
Fixes issue #18.
=> Adds reference to calling the script directly in the README.

src/Plugin.php
Changes the search depth to start from 0, when PHP_CodeSniffer is version 3.x or newer. This also points the path of `installed_paths` for this PHP_CodeSniffer version directly to the coding standard instead of the parent directory.
#26 Add support for code standards in root of repository for PHP_CodeSniffer 3.x
=> Support for coding standard in the root repository for PHP_CodeSniffer v3.x

src/Plugin.php
Changes the behavior of registering installed_paths in PHP_CodeSniffer 3.x. It will now work in the same way as was required for PHP_CodeSniffer 2.x. It will record the directory ABOVE the directory containing the coding standard. The only exception is when the root project itself provides the standard in the root of its project.
> [#33 Incorrect relative paths for WPCS](#33)
=> Fixes #33. Changes the way the installed_paths are set.

README.md
The script will install (register) one or more _Standards_ to PHP CodeSniffer, not the individual _Sniffs_.
Rename the script example in the Docs to clarify intent.
Optionally, it calls also be called `register-codestandards`, since the installation of the files has already been done by Composer, and this script would just re-register the Standard with PHP CodeSniffer. I've left it as `install-codestandards` for now though, as it may be perceived to be easier to remember, even if not technically accurate.
=> Docs: Rename example script

composer.json, phpcs.xml.dist
This plugin already has PHP_CodeSniffer as a dependency, but the project itself should also be checked against code standards.
While PSR-2 is already included, it would be useful to also check that the code supports down to the PHP 5.3 version specified in the Travis CI config file.
The inclusion of the `script` is so that those developing this repo can easily register the PHPCompatibility standard.
This is a prelude to #39.
=> Local PHPCS

composer.json, src/Plugin.php
Logically follows on from #38, though isn't strictly dependent on it being merged.
The use of short syntax for arrays was the only thing stopping this package from being compatible with PHP 5.3 as well. PHP 5.3 is specified in the Travis CI config. Allowing it to be used in setups that require PHP 5.3 makes it usable for more authors (such as those in the WordPress community).
Composer also requires PHP 5.3.2 to run, so it makes sense to ensure it works with that too.
=> CS: Add PHP 5.3 compatibility

README.md
Fixing a broken link to the releases in the `README.md` file.
=> Docs: Fix link to releases

README.md, composer.json
Switches the `PHPCompatibility` dependency over to use the repo in the `PHPCompatibility` GitHub organisation rather than the one in `wimg`'s personal account.
Includes updating the reference to the repo in the `Readme.md` file.
* https://github.com/PHPCompatibility/PHPCompatibility/issues/688
* https://github.com/PHPCompatibility/PHPCompatibility/releases/tag/8.2.0
=> Build/PHPCS: update PHPCompatibility repo name

README.md
Remove the VersionEye badge from the readme.
The VersionEye service has been terminated. I recommend turning off the webhook for checking PRs and such as well.
* https://github.com/versioneye/versioneye/issues/730
* https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/
=> README: remove VersionEye badge

README.md
The `year` part of the Shields.io `maintained` badge needs to be updated with the current year for it not to show as "No" (unmaintained/abandoned).
I'd like to suggest using a different badge - "Last commit" - instead which doesn't need manual updating each year and still gives a reasonable indication of the maintenance status of the project.
* https://shields.io/#/examples/other
=> README: replace maintenance badge

.travis.yml, composer.json
sensiolabs/security-checker introduced a change in 4.1.6 that makes the phar only compatible with PHP 7.1+
1. Use composer to manage the required version of security-checker instead of downloading via curl
2. Execute `phpcs` and `security-checker` from `/vendor/bin` instead of the phar files.
- #49 
- sensiolabs/security-checker#103
=> Execute phpcs and security-checker from vendor/bin

.gitattributes, .gitignore, phpcs.xml.dist
* Add the PHPCS custom ruleset to the `export-ignore` list in `.gitattributes`.
* Add the files which can be used by individual devs to overrule the project PHPCS ruleset to the `.gitignore` file.
* Strip down the file paths PHPCS shows in reports to the path relative to the project root.
=> PHPCS: various minor tweaks

.travis.yml, composer.json
:warning: PR #52 is a pre-requisite for this PR :warning:
This PR builds onto the changes made in PR #52 by @gapple and PR #52 should be merged first (if accepted). After that, this PR should be rebased to make it mergeable. Please feel free to ping me to rebase.
* Fix the PHP 5.3 build by instructing Travis to use the `precise` image instead of the `trusty` image for which PHP 5.3 is no longer available.
* Don't allow the PHP 5.3/5.4/5.5 builds to fail. After PR 52, they shouldn't be failing anymore, so there's no need to allow them to fail.
* Run the PHPCS code style and cross-version compatibility check only once.
All PHPCS sniffs are unit tested and written to give the same results on all supported PHP versions, so there is no need for the PHPCS check to be run on each and every …
=> Travis: various tweaks

CONTRIBUTING.md, composer.json, src/Plugin.php
Updates my personal & company contact information in multiple places in the repository.
n/a
=> Updates contact information

README.md
Several documentation updates to the README.
n/a
=> Updates README, spelling/grammar, removed Working section

.travis.yml, src/Plugin.php
The plugin executes `phpcs` when initialized, which may cause it to include the autoloader while it's in an inconsistent state.
For example, if a package that includes a static file is removed during an update (e.g. a compat library that provides global PHP functions):
1. Composer removes the outdated package from the file system
2. The phpcodesniffer-composer-installer plugin is initialized and attempts to use the autoloader files on disk
3. The outdated autoloader files on disk require the file from the removed package, and the composer update / install fails with a fatal error.
This PR moves the initialization of `installedPaths` to the method which responds to the `POST_INSTALL_CMD` and `POST_UPDATES_CMD` events, so that it is only initialized just before it's actually needed.
Fixes …
=> Move loadInstalledPaths from init to onDependenciesChangedEvent

README.md, src/Plugin.php
This MR add the ability to set the max-depth of the finder from the "extra" section of the `composer.json` file. 
The name of the key is `phpcodesniffer-max-depth`. This can be changed if a better suggestion is made.
The value has the constraint that:
- It MUST be an integer (not a numeric string)
- Not smaller or equal to the minimum level (which is `0` or `1` depending on the version of PHPCS installed)
- Not so large it is converter to scientific notation (which registers as a float) as this triggers an exception from the Finder class.
If the constraint is not met an exception is thrown informing the user.
Fixes #45
=> Adds the ability to set the max depth from the composer.json file

src/Plugin.php
Replaces `Symfony\Component\Process\ProcessBuilder` by `Composer\Util\ProcessExecutor`.
The `ProcessBuilder` does no longer exist in the Symfony `Process` package as of `4.0`.
By replacing it with Composers own executor, we avoid the issues for the future as well.
Fixes: #59
Fixes: wp-cli/package-command#99
=> Replaces ProcessBuilder by ProcessExecutor

src/Plugin.php
Refactors the way the Plugin figures out the relative paths from PHP_CodeSniffer to the Coding Standard. Replaces our own logic with methods provided by Composer itself.
n/a
=> Refactors relative path logic

src/Plugin.php
Ensure absolute paths during install paths detection phase.
In case a relative path is found, an absolute path is created (and cleaned up).
This also reduces the number of `getcwd()` calls throughout the Plugin.
Ref #63
=> Ensures absolute paths during detection phase

src/Plugin.php
Some trivial code changes (mainly sorting stuff). Little bit OCD 😉 
n/a
=> Trivial code cleanup

src/Plugin.php
I'm really unsure where this went wrong...
Fixes duplicate declaration of `$cwd`.
n/a
=> Fixes duplicate declaration of cwd

.travis.yml
Removes checks against HHVM from TravisCI.
Reasoning:
- HHVM builds are failing
- Almost impossible to fix
- HHVM discourages the use of HHVM for PHP projects
Source: https://github.com/facebook/hhvm#hhvm
> HHVM is intended for Hack projects, and also supports a large subset of PHP 7 that is required by common tools and libraries. We no longer recommend using HHVM for purely PHP projects.
n/a
=> Removes HHVM from TravisCI

.travis.yml
Currently the Travis build is breaking because the URL used by the security-checker no longer exists.
This MR updates that URL to the new home in order to fix the build.
It also adds a preview for PHP 7.4 and makes minor changes to improve the build step.
=> Update Travis file and fix build

src/Plugin.php
Add support for a string value of the `extra.phpcodesniffer-search-depth` config value so it can be set from the command line (`composer config`).
https://github.com/Dealerdirect/phpcodesniffer-composer-installer/issues/82
=> Add support for a string phpcodesniffer-search-depth config value set via `composer config`

phpcs.xml.dist, src/Plugin.php
PHPCS 3.5.0+ contains a far more complete PSR12 ruleset.
1. The current code didn't fully comply with that ruleset. Some minor code tweaks fix that.
2. PSR12 demands constant visibility to be declared, but as this project still supports PHP 5.3 and constant visibility wasn't introduced until PHP 7.1, this is not desirable. Excluding that particular rule from within the ruleset fixes that.
* https://github.com/squizlabs/php_codesniffer/releases
=> CS: fix compliance with PSR12

.travis.yml
As no code coverage is being generated, having Xdebug enabled is not needed and disabling it, should speed up build time.
=> Travis: disable Xdebug

.travis.yml
Using a normal `composer install` means that while the build was testing against various PHP versions, it would only ever test against the latest PHPCS 3.x version (`3.5.3` at the time of writing) for PHP 5.4-7.4 and PHPCS 2.9.2 for PHP 5.3.
This PR changes the build matrix to test against a variety of PHPCS versions to try to ensure compatibility with all versions this plugin claims to support.
Some explanation is needed about the choices made in this changeset:
The `install` section is intended for installing prerequisites for test build tests.
AFAICS, this wasn't previously used to avoid the PHP `lint` command running over the `vendor` directory, but that can be solved by just removing the `vendor` directory from the list PHP `lint` is run over.
Having the install instructions in the …
=> Travis: use a mix of PHPCS versions in the matrix

src/Plugin.php
Related to #79.
When the setting of `installed_paths` fails, show an error instead of giving the impression that the setting of the `installed_paths` succeeded.
Possibly not the best way to do this, but it does work, so consider this a proof of concept, if not the solution.
The `getPhpExecCommand()` method in the `Composer\EventDispatcher\EventDispatcher` class basically does what is needed: find the PHP executable used by Composer and turn it into an executable command.
Unfortunately, that method is `protected`, making it difficult to call that method from within the plugin.
This now copies that method into the plugin and uses it to create the command to pass on to the `ProcessExecutor`.
The copied method has some minor modifications to comply with the coding standards used within this …
=> Respect PHP version used by Composer and provide better feedback on failure

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md
Add some additional guidance in an attempt to make sure that enough information will be added to issues to make them actionable.
Having a singular issue template named `.github/ISSUE_TEMPLATE.md` is using the legacy workflow from GitHub.
GitHub nowadays recommends for issue templates to be placed in a `ISSUE_TEMPLATE` directory and to use front matter, to allow for multiple descriptive issue templates.
Ref: https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates
=> Improve GH issue template

README.md
When an external PHPCS standard itself is dependent on one or more other external standards, it can hep to have this plugin as a `require`ment for the external standard itself.
This commit adds a section about this feature, when to use it, why to use it and how to use it.
Includes minor grammar fix in existing text.
=> Readme: add section about including this plugin from an external PHPCS standard

src/Plugin.php
This fixes the issue identified in https://github.com/Dealerdirect/phpcodesniffer-composer-installer/pull/80#issuecomment-531586417 where even when the setting of `installed_paths` failed, the plugin would exit with exit code `0`.
A `0` exit code will be returned if successful, `1` - or the exit code returned by PHPCS itself - if not.
This will allow wrapper scripts and/or process scripts which take exit codes into account to fail correctly and/or notify users of failure.
1. On this repo, throw away the `vendor` directory and `composer.lock` file.
2. Make sure you are on the `master` branch.
3. Run `composer install`.
4. Now for the sake of testing this change, copy the `vendor/squizlabs/php_codesniffer/CodeSniffer.conf.dist` file to `vendor/squizlabs/php_codesniffer/CodeSniffer.conf` and …
=> Send an exit code when the script terminates

.github/workflows/linting.yaml, .yamllint
Adding github actions for linting, because travis can be very slow, i want to run the basic checks in github actions. If that works for use i want to expand it till we no longer need/use travis
=> Adding linting jobs in github action

.github/workflows/linting.yaml
* Fix the description for two of the builds.
* Remove the PHPCompatibility build as this is already included in the PHPCS build.
See: https://github.com/Dealerdirect/phpcodesniffer-composer-installer/blob/8bcaa7c245e3d2a6325f45aa94754e1d1b67d1a2/phpcs.xml.dist#L15-L16
=> GH Actions: minor tweaks:

.github/ISSUE_TEMPLATE/bug_report.md
What with the bug reported via PR #98, I believe it will be useful to always ask people to paste their config in an issue report.
=> Bug report template: further enhancement

src/Plugin.php
Discovered while debugging the build failure of #97
The PHPCS `--config-show` command shows **all** config settings set, not just the `installed_paths` and since PHPCS 3.1.0, it also includes a line to indicate which configuration file is being used to help with debugging configuration issues.
Example:
```
Using config file: I:/path/to/project/vendor/squizlabs/php_codesniffer/CodeSniffer.conf
default_standard:  Squiz
installed_paths:   ../../phpcompatibility/php-compatibility
show_progress:     1
```
In PHPCS 2.0 - 3.0.1, if any [other configuration options](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options) were set, aside from `installed_paths`, the result of the `loadInstalledPaths()` command would be broken.
In PHPCS 3.1.0+, the result would always be broken, no …
=> Bug fix: `loadInstalledPaths()` very very broken since PHPCS 3.1.0

src/Plugin.php
As most problems reported are to do with paths not being set correctly, let's verify success within the plugin, independently of PHPCS.
To that end, a new function `verifySaveSuccess()` has been added.
This function takes the paths which were to be saved and compares them to the paths which are actually set in PHPCS after the save to determine whether or not the plugin was successful and changes the exit code if this is not the case.
Open questions:
* Should additional debug output be generated by the verification function when `verbose` mode is turned on ? Something like `Expected paths to be set to: %s, found: %s`.
This could also come in handy to verify that all paths which should be set were found by the plugin.
At this moment I don't have a test case for this new functionality, …
=> Verify the `installed_paths` after save

src/Plugin.php
If the phpcodesniffer-composer-installer plugin is installed as a dev
requirement and it is then uninstalled as part of a "--no-dev" install, a bug
occurs. The bug that occurs is that the plugin complains that the  package
"squizlabs/php_codesniffer" is not installed without checking if the package
should be present.
This commit adds a check to verify that this plugin is actually installed before
complaining about the missing package. If this plugin itself is removed, then
it should not complain about the missing package.
#103
=> Fix for issue #103

src/Plugin.php
After the 0.6.0 update, Composer's `scripts/post-install-cmd` and `scripts/post-update-cmd` were no longer running.
This was due to PHP _exiting_ outright rather than _returning_ the `$exitCode`.
=> Bugfix: Composer scripts/commands broken in 0.6.0 update

.travis.yml, composer.json
As it was, the plugin when used by external standards, would block them from being tested on PHP 8.
As all the dependencies in the `require` section allow for PHP 8, there is no reason not to allow it.
The only dependencies currently in use which do not allow for PHP 8 yet are in the `require-dev` section. See the below output.
This includes updating the Travis script to:
* Only do a full (`dev`) install when not on `nightly`.
* Ignore platform requirements on `nightly` as otherwise the `dev` requirements would still block installation.
* And as PHPCompatibility is in the `require-dev` section, we need to require it explicitly for `nightly` to make sure the integration test can run.
As the Travis build on PHP `nightly` passes, I'm semi-confident that all should be good, though confidence …
=> Allow installation on PHP 8

.travis.yml, composer.json
Development for PHPCS 4.x has started in a new `4.0` branch.
This PR is two-fold:
1. On the one hand, it adds testing against PHPCS 4.x to the Travis matrix as an early warning system in case any cross-version compatibility fixes would be needed for the plugin itself.
The build against `4.x-dev` has been added to `allow_failures` for now.
Note: as PHPCompatibility currently doesn't allow for PHPCS 4.x (yet), I'm aliasing the install to `3.9.99` for testing purposes in the Travis build only.
2. On the other hand, it allows installation in combination with PHPCS 4.x, which will in turn allow external standards which `require` this plugin, to start testing their standard against the PHPCS 4.x-dev branch.
As it was now, external standards would get the plugin at version `0.4.4` as that's the …
=> Test with PHPCS 4.x and allow installation when using PHPCS 4.x

composer.json, src/Plugin.php
Minimal changes to updated the plugin to support Composer 2.0 which is expected late May/beginning of June.
Tested by @danepowell and myself (Windows 7). Further testing would be very welcome!
Fixes #108
@mjrider @Potherca Should this be added to the `0.6.3` or `0.7` milestone ?
Changes are based on guidance found in:
* https://github.com/Dealerdirect/phpcodesniffer-composer-installer/issues/108
* https://github.com/composer/composer/issues/8726
* https://github.com/composer/composer/blob/master/UPGRADE-2.0.md#for-integrators-and-plugin-authors
=> Support Composer 2.0

composer.json
`4.0.x-dev` is the name of a branch, and not a version constraint. You should use a proper version constraint, otherwise anyone else who does use a one will find composer doesn't know what to do.
=> Fixed v4 constraint

.remarkrc, README.md
This MR adds a configuration file for Remark, so there is now one consistent way Markdown should be written in this repo.
The configuration uses the `lint-recommended` preset, with as only exception that the `list-item-indent` has been set to only require a single space after a list character (as opposed to the multi-space default).
Other than a few links in the README, all markdown files in the repo already adhere to this standard.
As there is already a GitHub action that runs Remark, no other changes are needed.
This MR is inspired by the comment from @jrfnl in #118 regarding inconsistencies in my Markdown.
I suggested adding a Remark config, so here it is! :grin:
=> Add remark configuration

src/Plugin.php
> Fixes the inconsistency in `installed_paths` documented in #125 by sorting the list of installed paths alphabetically before saving them.
> #125
=> Sort list of installed paths before saving for consistency

src/Plugin.php
While looking into the (non-)race condition described in #125, I noticed a potentially related issue.
As per the documentation of [realpath()](https://www.php.net/manual/en/function.realpath.php#refsect1-function.realpath-returnvalues):
> realpath() returns FALSE on failure, e.g. if the file does not exist.
In the rare case that `realpath()` _would_ return `false` within this plugin, `false` would subsequently be passed on to `is_dir()` and `is_readable()` which both expect a string path.
This tiny change makes the condition fail earlier by checking the return value of `realpath()`.
=> Stabilize a condition

.travis.yml
Use multi-line conditions to reduce line-length.
Note: this doesn't solve all the "warnings" and AFAICS, the other warnings can't really be solved anyhow as it would necessitate breaking up command to multiple lines which would break the command.
#123
=> Travis: line length tweaks

README.md
=> Add mention of Composer and PHP compatibility to project README.

.github/workflows/integrationtest.yml, composer.json
* No longer allow builds against PHP 8.1 to fail.
* Add a dedicated build against PHP 8.1 in combination with the lowest PHPCS version which supports it (runtime support).
* Change the experimental `nightly` build to use PHP 8.2.
Includes updating the version constraint for the PHP Parallel Lint tool to have the minimum version set to a version which supports PHP 8.1.
=> GH Actions: PHP 8.1 has been released

README.md
As of Composer 2.2.0, Composer plugins need to be explicitly allowed to run.
This updates the readme to inform users of this mechanism.
Ref: https://blog.packagist.com/composer-2-2/#more-secure-plugin-execution
... to be a little more realistic for current dev.
=> README: update with information about Composer >= 2.2

.yamllint
This MR adds a config rule to the Yaml Lint config to prevent the warning
> truthy value should be one of [false, true]
to occur in GitHub Action files for the key `on`.
This should cut down on false positives. Line-lenght warnings still need to be resolved.
=> Change YamlLint config to prevent "truthy" warning.

.github/workflows/integrationtest.yml, .github/workflows/linting.yaml, .github/workflows/phplint.yml, .github/workflows/quicktest.yml, .github/workflows/securitycheck.yml, src/Plugin.php
PHPCS 3.6.2 added a sniff for a PSR-12 rule which was previously not strictly checked: "No blank line after the opening brace of a class".
This fixes the newly flagged issues.
Previously, in Travis, when the same branch was pushed again and the "Auto cancellation" option on the "Settings" page had been turned on (as it was for most repos), any still running builds for the same branch would be stopped in favour of starting the build for the newly pushed version of the branch.
To enable this behaviour in GH Actions, a `concurrency` configuration needs to be added to each workflow for which this should applied to.
More than anything, this is a way to be kind to GitHub by not wasting resources which they so kindly provide to us for free.
Refs:
* …
=> CI: various updates

CONTRIBUTING.md
PR #117 updated the code of conduct and moved it to a dedicated file, however, it looks like PR #118 accidentally re-introduced it into the `CONTRIBUTING` file.
Removing the text now from the `CONTRIBUTING` file (again).
=> CONTRIBUTING: remove duplicate code of conduct

CONTRIBUTING.md
=> Add details regarding QA automation in CONTRIBUTING.md file.

CONTRIBUTING.md, LICENSE.md, README.md, composer.json, phpcs.xml.dist, src/Plugin.php
Just a couple of commits with minor tweaks for things I noticed along the way.
.. for improved code readability and consistency.
Only just noticed that it hadn't been adjusted for the move of the CoC to a separate file.
=> Various minor tweaks

composer.json
Some of the early PHPCS 3.x versions did not support external standards correctly, so using this plugin with those would always run into trouble, so let's just make it explicit that `3.0.0` and `3.0.1` are not supported.
`3.0.2` should be fine, though IIRC, even `3.1.0` contained some fixes for external standard support, so we could choose to up this to `^3.1.0` to be on the safe side.
=> Composer: tweak PHPCS version constraint

src/Plugin.php
Running PHPCS with `--config-show installed_paths` is an unsupported command for PHPCS. The `--config-show` command does not take additional parameters and will always show all keys.
While PHPCS is currently tolerant of this, there is no guarantee that it will continue to stay tolerant of this.
=> Plugin::loadInstalledPaths(): `config-show` always shows all

.github/workflows/integrationtest.yml, .github/workflows/phplint.yml, .github/workflows/quicktest.yml, .github/workflows/securitycheck.yml, README.md, composer.json, phpcs.xml.dist
This PR just and only drops support for PHP 5.3. It doesn't (yet) take advantage of features which were introduced in PHP 5.4, which could now be used.
Fixes #145
=> Drop support for PHP 5.3

README.md
Looks like the connection with Scrutinizer was broken more than 3 years ago, so the score is by now out of date and because of that irrelevant.
Ref: https://scrutinizer-ci.com/g/dealerdirect/phpcodesniffer-composer-installer/
=> README: remove references to Scrutinizer

tests/PHPCSVersions.php
... after #146 / #158. (there was one ref to the old repo location in the open PR)
=> PHPCSVersions: update URL references

tests/IntegrationTest/BaseLineTest.php
BaseLineTest: stabilize the message checks by using the constant declared in the class under test instead of the actual content of the message.
=> BaseLineTest: stabilize the message checks

.github/workflows/integrationtest.yml
Run integration tests against Composer snapshot for a limited set of builds to get early warning of upcoming changes we need to be aware of.
It has already been announced that Composer 2.3 will drop support for PHP < 7.2 and there may be more breaking changes, so seeing test failures early would seem a good thing (both to fix things in the plugin, if needs be, as well as to report issues with the next version of Composer upstream).
=> GH Actions: run integration tests against Composer snapshot

tests/TestCase.php
Retry Composer commands on a particular exception as otherwise a complete build may fail, while the failure is not related to an actual test failure,
I've seen this particular issue a couple of times in test runs (most typically with the problematic Composer v1 / PHP 5.5 / Windows combination).
Adding a one-time only retry of a command run and only for that particular issue should prevent having to re-run a complete build for this.
=> TestCase::executeCliCommand(): retry Composer commands on a particular exception

tests/IntegrationTest/RegisterExternalStandardsTest.php, tests/TestCase.php, tests/fixtures/README.md, tests/fixtures/dummy-src/composer.json, tests/fixtures/dummy-src/src/DummySrcSubDir/ruleset.xml, tests/fixtures/multistandard/My-Third-Standard/ruleset.xml, tests/fixtures/multistandard/MyFirstStandard/ruleset.xml, tests/fixtures/multistandard/MySecondStandard/ruleset.xml, tests/fixtures/multistandard/composer.json
... as a helper to allow for comparing expected and actual registered paths from `--config-show`.
* As the behaviour shouldn't be different between Composer local/global, the test is only run against one of these (local).
* The test is, however, run against multiple PHPCS versions to ensure the path to the standard as registered allows for picking up all expected rulesets in all supported PHPCS versions.
Includes adding a fake standard with multiple rulesets as a fixture for this test.
* As the behaviour shouldn't be different between Composer local/global, the test is only run against one of these (global).
* The test is run against one random PHPCS version as with the other tests in place, sufficient PHPCS versions are being tested.
Even though this means there is only _one_ test case, …
=> RegisterExternalStandardsTest: add new tests

tests/IntegrationTest/PreexistingPHPCSConfigTest.php
This new test class tests that the plugin handles a pre-existing PHPCS configuration file correctly.
These tests verify:
- That the plugin will add the `installed_paths` setting correctly.
- That the plugin does not remove or alter existing configurations, except for the `installed_paths`.
Notes:
* As PHPCS behaves the same whether installed locally or globally, it is unnecessary to run the tests in both type of environments.
* As the output of the `config-show` command in PHPCS has changed across PHPCS version, it is necessary to test against multiple PHPCS versions.
This test class covers the following bug previously reported:
* Dealerdirect/phpcodesniffer-composer-installer PR #98
Related to #92
=> Tests: add new `PreexistingPHPCSConfigTest`

src/Plugin.php, tests/IntegrationTest/PreexistingPHPCSInstalledPathsConfigTest.php
This new test class tests that the plugin handles a pre-existing PHPCS configuration file, which includes an `installed_paths` setting, correctly.
These tests verify:
- That the plugin does not remove or alter any valid paths which already existed in `installed_paths`.
- That the plugin removes invalid paths which already existed in `installed_paths`.
Notes:
* While PHPCS behaves the same whether installed locally or globally, it is still necessary to run the tests in both type of environments.
Bug composer/composer#10504 (discovered while writing these tests) is example of the reason why.
To not create too much redundancy, I've elected to run one of the tests via Composer global and the other one via local.
* As the output of the `config-show` command in PHPCS has changed across PHPCS …
=> Tests: add new `PreexistingPHPCSInstalledPathsConfigTest` + bug fix

tests/IntegrationTest/InvalidPackagesTest.php, tests/fixtures/README.md, tests/fixtures/incorrect-type/IncorrectType/ruleset.xml, tests/fixtures/incorrect-type/composer.json, tests/fixtures/no-ruleset/NoRuleset/ruleset.xml.dist, tests/fixtures/no-ruleset/composer.json
This new test class tests that the plugin does not act on Composer packages which are not considered valid external PHPCS standards for the purposes of this plugin.
Notes:
* This test is about Composer and the plugin, so does not need to be tested against multiple PHPCS versions.
* The behaviour also shouldn't differ between a global vs local Composer install, so only testing one type.
Related to #92
=> Tests: add new `InvalidPackagesTest`

tests/IntegrationTest/PlayNiceWithScriptsTest.php
This new test class tests that the plugin does not block other post install/update scripts from running.
I have confirmed that this test as-is would fail in combination with the `0.6.0` and `0.6.1` versions of the plugin and would pass with `0.5.0`, `0.6.2` and current.
For confirmation see this build against `0.6.0`: https://github.com/Dealerdirect/phpcodesniffer-composer-installer/actions/runs/1787983161 (only run against Composer 1 as `0.6.0` was not compatible with Composer 2 yet).
Notes:
* This test is about Composer and the plugin, so does not need to be tested against multiple PHPCS versions.
* The behaviour also shouldn't differ between a global vs local Composer install, so only testing one type.
This test class covers the following bug previously reported:
* …
=> Tests: add new `PlayNiceWithScriptsTest`

.github/workflows/integrationtest.yml, .github/workflows/linting.yaml, .github/workflows/phplint.yml, .github/workflows/quicktest.yml, .github/workflows/securitycheck.yml
A number of predefined actions have had major release, which warrant an update the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
=> GH Actions: version update for various predefined actions

tests/IntegrationTest/RegisterExternalStandardsTest.php
Looks like the build for one of the new PRs is failing on the Composer v1 / Windows / PHP 5.5 build, which is notorious for not always showing the output from the plugin, even though the plugin does work.
This minor change should stabilize that test for that particular build.
Also see: https://github.com/PHPCSStandards/composer-installer/commit/d4f64b822a76e1aac325f18ac160b9daac01ff49
=> RegisterExternalStandardsTest: stabilize test for Composer v1 on Windows with PHP 5.5

.github/workflows/integrationtest.yml, tests/bootstrap.php
Composer 2.3 drops support for PHP < 7.2, so for PHP 5.4 to 7.1, `v2` will install Composer 2.2, for PHP 7.2 and up, `v2` will install Composer 2.3.
These extra builds make sure the Composer 2.2 LTS version will continue to be 100% supported for PHP 7.2-8.x.
Refs:
* https://blog.packagist.com/composer-2-3/
* https://github.com/composer/composer/releases/tag/2.3.0
Apparently, Composer 2.3.0 dropped the word `version` from the `--version` output ;-)
Output on Composer 2.2 and lower:
```
Composer version 2.2.10 2022-03-29 21:55:35
```
Composer 2.3 output:
```
Composer 2.3.0 2022-03-30 11:15:36
```
=> GH Actions: add builds against Composer 2.2 for PHP 7.2 - 8.x

.github/workflows/linting.yaml, .github/workflows/phplint.yml, .github/workflows/securitycheck.yml
1. Currently, YamlLint complains about the line-length in `securitycheck.yml` GitHub Worflow.
This MR resolves that violation by adding a comment telling YamlLint to ~~shut the fuck up~~ kindly ignore that specific line.
(see https://yamllint.readthedocs.io/en/stable/disable_with_comments.html for documentation details).
2. As using `on:` as a key name is no longer marked as a violation (by the `truthy` rule configuration in the `.yamllint` file), the following diable comment has been removed in all files that had it:
```yml
```
=> Update YamLint 

tests/IntegrationTest/InstallUpdateEventsTest.php, tests/IntegrationTest/NonInstallUpdateEventsTest.php
Test that the plugin is hooked into the right events and doesn't get triggered when those events are blocked (`--no-plugins`).
These tests verify that:
- The plugin gets triggered on install/update/require/remove/reinstall events.
- The plugin doesn't run when Composer is run with `--no-plugins`.
- The plugin does run when Composer is run with `--no-scripts` ([since Composer 2.1.2](https://github.com/composer/composer/pull/9942)).
- Can be run on-demand via a custom script.
This test is about Composer and the plugin, so does not need to be tested against multiple PHPCS versions.
The behaviour also shouldn't differ between a global vs local Composer install, so only testing one type.
Note: the `composer reinstall` test will only run on Composer 2.2.6+ as [prior to that release plugins …
=> Tests: add new InstallUpdateEventsTest and NonInstallUpdateEventsTest

tests/IntegrationTest/RemovePluginTest.php
Test that the plugin does not throw errors when the plugin is still in memory, but PHPCS and the plugin are uninstalled (Composer 1.x).
These tests verify:
- That the plugin exits with error code 0 when PHPCS and the plugin are uninstalled due to a no-dev install.
- That the plugin exits with error code 0 when the standard which required the plugin is uninstalled.
This test is about Composer and the plugin, so does not need to be tested against multiple PHPCS versions.
The behaviour also shouldn't differ between a global vs local Composer install, so only testing one type.
Note: the behaviour of Composer changed for this in Composer 2.0.0, but still not a bad thing to safeguard this for Composer 2.x as well, in case of regressions in Composer.
This test class covers the following bug …
=> Tests: add new `RemovePluginTest`

tests/IntegrationTest/PlayNiceWithScriptsTest.php, tests/TestCase.php
Yet another one which intermittently fails on the notorious PHP 5.5 / Composer 1.x on Windows combination.
(saw it fail in two of the test runs for the new PRs, though, like in most cases: not always)
=> PlayNiceWithScriptsTest: wrap output expectation in condition

.github/workflows/integrationtest.yml, .github/workflows/quicktest.yml
Looks like the `zip` extension is not available by default on [Windows with PHP 8.2](https://github.com/shivammathur/setup-php/wiki/Php-extensions-loaded-on-windows-2019#php-82), which is causing those builds to fail as the zip extension is needed in the test bootstrap.
Looking at the `composer.json` file, we previously identified the `json` and `zip` extensions as `dev` requirements, so let's ensure they will always be [installed and enabled in CI](https://github.com/shivammathur/setup-php#heavy_plus_sign-php-extension-support).
=> GH Actions: fix builds on Windows with PHP 8.2

tests/IntegrationTest/InstalledPathsOrderTest.php
This new test class tests that the plugin always registers the `installed_paths` in the same order.
I have confirmed that the tests would fail on various CI builds without the fix from #126.
Notes:
* This test is about Composer and the plugin, so does not need to be tested against multiple PHPCS versions.
This test class covers the following bug previously reported:
* Dealerdirect/phpcodesniffer-composer-installer#125
* Dealerdirect/phpcodesniffer-composer-installer#126
Related to #92
=> Tests: add new `InstalledPathsOrderTest`

src/Plugin.php, tests/IntegrationTest/RootPackageHandlingTest.php, tests/TestCase.php
New helper method to recursively copy a (fixture) directory with all its files to another location, typically, one of the system temp test directories.
If the `$srcDir` contains a `composer.json` file, it will get the same `TestCase::writeComposerJsonFile()` special treatment, meaning that the artifacts directory will be injected, as well as plugin permissions and more.
This new test class tests that the plugin correctly registers standards found in the root package if it is an external standard.
Notes:
* This test is about Composer and the plugin, so does not need to be tested against multiple PHPCS versions.
This test class covers the following bugs previously reported:
* Dealerdirect/phpcodesniffer-composer-installer#19
* Dealerdirect/phpcodesniffer-composer-installer#21
* …
=> Tests: add new RootPackageHandlingTest + bugfix

src/Plugin.php
The `Nothing to install or update` message is confusing, as for an end-user, it may not be clear that this message relates to the PHPCS plugin.
The message as-is could be interpreted to relate to Composer itself finding _nothing to install or update_ instead.
I'd like to suggest changing that message to be more directly related to this plugin for clarity.
=> Plugin: improve feedback

.github/workflows/integrationtest.yml, tests/IntegrationTest/BaseLineTest.php, tests/IntegrationTest/InstallUpdateEventsTest.php, tests/IntegrationTest/PlayNiceWithScriptsTest.php, tests/IntegrationTest/PreexistingPHPCSInstalledPathsConfigTest.php, tests/IntegrationTest/RegisterExternalStandardsTest.php, tests/TestCase.php
As discussed in #181.
Fixes #181
This method was put in place in PR #153 (commit https://github.com/PHPCSStandards/composer-installer/commit/d4f64b822a76e1aac325f18ac160b9daac01ff49) as a work-around for the problematic PHP 5.5 / Composer v1 on Windows build.
As we won't be running the tests against that particular combination anymore, I propose we remove all these work-arounds from the test suite.
This effectively reverts the following commits (and a little more):
* f0251b838a3c0461056192db13d4dab66bc7d013.
* ccd127f5676213d57ba5fd29fc181b6a2c5972b0.
* d4f64b822a76e1aac325f18ac160b9daac01ff49.
#181
=> GH Actions: stop running tests against PHP 5.5/Composer 1.x on Windows (and remove work-arounds)

.github/workflows/securitycheck.yml
The security checker binary has had a new release with improved handling for when a package has multiple security issues.
Refs:
* https://github.com/fabpot/local-php-security-checker/releases
* https://github.com/fabpot/local-php-security-checker/pull/52
=> GH Actions/Securitycheck: update the security checker download

.github/workflows/integrationtest.yml, .github/workflows/phplint.yml, .github/workflows/quicktest.yml, .github/workflows/securitycheck.yml, tests/PHPCSVersions.php
The security checker binary has had a new release, so let's take advantage of it.
Refs:
* https://github.com/fabpot/local-php-security-checker/releases
* https://github.com/fabpot/local-php-security-checker/blob/v2.0.6/CHANGELOG.md
PHP 8.2 has been released today 🎉 and the `setup-php` action has announced support for PHP 8.3, so adding PHP 8.3 to the matrix and no longer allowing PHP 8.2 to fail the build.
Builds against PHP 8.3 are still allowed to fail for now.
... of the bash `date` command in the earlier pulled cache busting.
=> GH Actions: various tweaks / PHP 8.2 not allowed to fail

.github/workflows/integrationtest.yml, .github/workflows/quicktest.yml
I've seen some recent build failures (elsewhere) due to the `setup-php` action running into a rate limit and not downloading the required version of Composer. In the case of this package, that would make the test runs worthless.
The `setup-php` action runner defaults to _showing_ these type errors in the logs, but not stopping the workflow run.
So, specifically for those jobs where the Composer version is important, I'm adding the `fail-fast` option to `setup-php` to fail the build if the action runner ran into any errors.
Ref: https://github.com/shivammathur/setup-php#fail-fast-optional
=> GH Actions: selectively use `fail-fast` with setup-php

.gitattributes
A number of dev-related files/directories were not listed in the `.gitattributes` file, while these don't need to be included in the distribution archives.
Fixed now.
=> .gitattributes: sync with current repo state

README.md
=> Remove the projects stage "Development" badge

composer.json
Proposed Changes
Related Issues
Code scans mark it as insecure. Here it really does not matter as the side upgrades to https it is still good practise
=> Replace http with https

.github/workflows/integrationtest.yml, tests/PHPCSVersions.php
* Builds against PHP 8.3 are no longer allowed to fail.
* Add _allowed to fail_ build against PHP 8.4.
~~_I'm opening this in draft until one of us finds some time to figure out why the tests aren't running properly anymore and fixes that first._~~ PR #213 should fix the failing build. Once that PR has been merged, this one can be rebased & the build should pass.
* https://www.php.net/releases/8.3/en.php
=> GH Actions/test: PHP 8.3 has been released

.github/workflows/securitycheck.yml, composer.json
When working with this repository as a developer, we should be using the latest compatible packages. By writing a lock file for Composer, we may get into a state where we are "stuck" on an older version of a dependency. This change avoids such a situation by telling Composer to not write out a lock file in the project.
=> Composer: avoid writing a lock file

.github/workflows/integrationtest.yml
Composer 1.x is no longer supported and while Composer 2.2 is an LTS version, the LTS is only for critical bugs and security issues, not necessarily for supporting new PHP versions.
The LTS support was also officially only in effect until end of 2023 (and I have not seen any announcement of an extension).
In practice, this means the following:
* Composer 1.x and Composer 2.2. were previously made compatible with PHP 8.2 and 8.3 (released since the announcement).
* However, it is unlikely that Composer 1.x and Composer 2.2 will be made compatible with PHP 8.4 and builds against those combinations are already failing.
With the above in mind, I propose to stop running the tests against Composer 1.x/2.2 - PHP 8.4 combinations as they can only fail and those failures are not related to the …
=> GH Actions: stop testing with PHP 8.4 against Composer < current

README.md
The readme still contained various references to "minors being treated as majors below v1.0".
This information was relevant prior to the 1.0 release (and slightly after), but the `1.0` version has been out for over a year now and adoption is good with approximately 70% of users having updated to 1.0 so far.
This commit updates the README text to simplify the information related to this.
Refs:
* https://packagist.org/packages/dealerdirect/phpcodesniffer-composer-installer/stats
=> README: updates related to the 1.0 release + mention funding

.github/workflows/phplint.yml, composer.json
While rare, there are some deprecations which PHP can show when a file is being linted.
By default these are ignored by PHP-Parallel-Lint.
Apparently though, there is an option to show them (wasn't documented until recently), so let's turn that option on.
The PHP lint job currently checks all PHP files for parse/compile errors against a limited set of PHP versions, including the high/low versions.
It did not run the linter against the _next_ (upcoming) PHP version yet.
This has now been added with the `'nightly'` alias, which means that the version will automatically roll through to the next PHP version when a new PHP branchs gets cut, without us needing to manually maintain this.
Also note that the build against `nightly` is allowed to fail.
=> GH Actions: show deprecations when linting & lint against next PHP version

.github/workflows/integrationtest.yml, .github/workflows/phplint.yml, .github/workflows/quicktest.yml, .github/workflows/securitycheck.yml
Because of the amount of GitHub API calls composer does, the CI runs into a rate limit. This causes jobs to fail or be aborted. Adding the GITHUB_TOKEN as auth method _should_ avoid these rate limits.
- #196
=> Add COMPOSER_AUTH env variable to workflows

.github/workflows/securitycheck.yml
Only perform security check on actual dependencies / ignore development-only dependencies for this check.
https://github.com/PHPCSStandards/composer-installer/pull/228#issuecomment-2492542642
=> Ignore development-only packages in security check

.github/workflows/integrationtest.yml, README.md, tests/IntegrationTest/BaseLineTest.php, tests/IntegrationTest/RegisterExternalStandardsTest.php
Just some small things I saw in passing while reviewing PR #230.
=> Minor documentation fixes

.github/workflows/integrationtest.yml, .github/workflows/quicktest.yml, CONTRIBUTING.md, README.md, composer.json, tests/IntegrationTest/BaseLineTest.php, tests/IntegrationTest/InstallUpdateEventsTest.php, tests/IntegrationTest/RemovePluginTest.php, tests/TestCase.php
Composer themselves will no longer support version 1.x beyond 1st August 2025. Composer version 2.0 was released in October 2020, which is more than four years ago. Anyone wanting to use this plug-in with Composer v1.x can use any existing version.
https://blog.packagist.com/composer-2-0-is-now-available/
https://blog.packagist.com/deprecating-composer-1-support/
https://blog.packagist.com/shutting-down-packagist-org-support-for-composer-1-x/
- This is step one of three for https://github.com/PHPCSStandards/composer-installer/issues/221
=> Drop support for Composer v1.x

tests/bootstrap.php
The zip package we create in the test bootstrap to allow for Composer to use the root version of this package when installing needs to have a higher version number than any released version. The version number, however, should also be compatible with the current major.
This updates the version number in the test bootstrap file.
=> Tests: allow for tests to use root package

src/Plugin.php
The Composer runtime-api 2.0 introduced the `\Composer\InstalledVersions::isInstalled()` method.
This commit starts using that method.
Implementation choices:
While it would be possible to also handle the version checking via `Composer\InstalledVersions::satisfies(new VersionParser, self::PACKAGE_NAME, (string) $versionConstraint)`, this would require adding a new dependency `"composer/semver": "^3.0"`.
For now, I've chosen not to add the dependency and to leave the pre-existing code for handling version constraints.
Ref: https://getcomposer.org/doc/07-runtime.md#installed-versions
The Composer runtime-api 2.1 introduced the `\Composer\InstalledVersions::getInstallPath()` method.
This commit starts using that method.
Ref: https://getcomposer.org/doc/07-runtime.md#knowing-the-path-in-which- …
=> Plugin: use Composer API 2.x methods

phpcs.xml.dist, tests/PHPCSVersions.php, tests/fixtures/dummy-subdir/DummySubDir/Sniffs/Demo/DemoSniff.php, tests/fixtures/dummy-subdir/DummySubDir/dummy-autoload.php, tests/fixtures/dummy-subdir/DummySubDir/ruleset.xml
The PHP_CodeSniffer 4.0 branch has been completely rebuild. See https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/120 for more detailed information about the "why".
In practice, this means that to test against the upcoming PHPCS 4.0 release, we need to test against the `4.x` branch now, not the old `4.0` branch.
A 4.0 beta/RC release is expected in the next few days. Once that is out, a test period starts and depending on whether problems are found or not, the 4.0.0 release will be tagged about a month later (or later if significant problems were found).
When 4.0.0 gets tagged, the PHPCS `master` branch will be renamed to `3.x` and the `4.x` branch will be the new "main" branch for PHPCS, so more changes will be needed, but that's for later.
Includes updating the `DemoSniff` test …
=> Tests: run against the *new* PHPCS 4 branch

tests/fixtures/dummy-src/src/DummySrcSubDir/ruleset.xml, tests/fixtures/dummy-subdir/DummySubDir/ruleset.xml, tests/fixtures/incorrect-type/IncorrectType/ruleset.xml, tests/fixtures/multistandard/My-Third-Standard/ruleset.xml, tests/fixtures/multistandard/MyFirstStandard/ruleset.xml, tests/fixtures/multistandard/MySecondStandard/ruleset.xml, tests/fixtures/no-ruleset/NoRuleset/ruleset.xml.dist
PHPCS now offers permalinks for the schema.
Refs:
* PHPCSStandards/PHP_CodeSniffer#1094
* https://github.com/PHPCSStandards/schema.phpcodesniffer.com
=> Test fixture rulesets: update schema URL

src/Plugin.php
I'm very curious why the reported issue only appears to happen with a Drupal setup (and I cannot reproduce it, nor do our tests fail). All the same, I'm hoping this will fix it.
Note: yes, `realpath()` can return `false`, but that shouldn't be possible in this case as we only call it after we've already checked `isPHPCodeSnifferInstalled()`.
Fixed #239 (hopefully)
=> Fix "The provided cwd "../squizlabs/php_codesniffer" does not exist."

.github/workflows/integrationtest.yml, .github/workflows/phplint.yml, .github/workflows/quicktest.yml
Even though the workflows already set `env: COMPOSER_AUTH` since #200, we are still running into rate limiting issues.
This commit applies the [instruction from `setup-php`](https://github.com/shivammathur/setup-php#github-composer-authentication) on how to solve this. :crossed_fingers:
=> GH Actions: try to fix builds failing due to rate limiting

src/Plugin.php
This now reverts the second code modernization from #234 as well. Annoying, but so be it.
I've also now added warnings in both places which were modernized and for which the modernizations had to be reverted to hopefully prevent this happening again.
Fixes #247
Fixed
- Potential fatal error when the Composer EventDispatcher is called programmatically from an integration.
=> Fix fatal error when Composer EventDispatcher called programmatically

.github/workflows/integrationtest.yml, .github/workflows/phplint.yml, .github/workflows/quicktest.yml
As of the release of `shivammathur/setup-php` v`2.35.0`, this should no longer be needed as the `setup-php` action runner will automatically use the `secrets.GITHUB_TOKEN` token.
Ref:
* https://github.com/shivammathur/setup-php/releases/tag/2.35.0
* https://github.com/shivammathur/setup-php/commit/55463ffe4fef24b158d1d7f861dce8b7d3811c13
_N/A_
=> GH Actions: remove GH Token set via `env`

tests/PHPCSVersions.php
Follow up on #255, which missed making this change.
While not that relevant yet as the only PHPCS 4.x release is currently 4.0.0, this will become relevant once additional PHPCS 4.x releases have been tagged.
_N/A_ (test only change)
=> Tests/PHPCSVersions: improve handling PHPCS 4.x

tests/PHPCSVersions.php
The PHP native `min()` and `max()` versions were used to retrieve the lowest/highest PHPCS version from arrays of PHPCS versions.
This worked fine at the time this class was created as none of the supported PHPCS versions had a `*.10` minor (or higher) at the time.
However, this logic was broken as soon as the `3.10.0` release was tagged - see https://3v4l.org/XbHOY - , we just never realized until now.
Fixed now by adding custom `min`/`max` methods to the class.
---
Note: the first two commits are just girl-scouting while I was looking at the file anyway. The third commit is why I was looking at the file ;-)
_N/A_ (test only change)
=> Tests/PHPCSVersions: bug fix 
